from enum import Enum

class Classifier(Enum):
    WEEKLY_STOCK_SPECULATION_CLASSIFIER = "WEEKLY_STOCK_SPECULATION_CLASSIFIER"
    WEEKLY_CRYPTO_SPECULATION_CLASSIFIER = "WEEKLY_CRYPTO_SPECULATION_CLASSIFIER"
    QUARTERLY_STOCK_FINANCIAL_CLASSIFIER = "QUARTERLY_STOCK_FINANCIAL_CLASSIFIER"
    NONE = "NONE"