from enum import Enum

class Ranker(Enum):
    QUARTERLY_STOCK_EARNINGS_RANKER = "QUARTERLY_STOCK_EARNINGS_RANKER"
    QUARTERLY_STOCK_DIVIDENDS_RANKER = "QUARTERLY_STOCK_DIVIDENDS_RANKER"
    QUARTERLY_STOCK_ROLLING_RANKER = "QUARTERLY_STOCK_ROLLING_RANKER"
    WEEKLY_STOCK_ROLLING_RANKER = "WEEKLY_STOCK_ROLLING_RANKER"